### ISSUE TITLE
Remove CircleCI - replace nightly with GitHub Actions

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail-hallo#10]
> ## CI setup
> 
> It feels overkill to me we’re using both CircleCI and GitHub Actions on this project. The main reason CircleCI is used for Wagtail core is because we have so many frequent builds on GitHub Actions – so it’s nice to have basic linting finishing sooner. For a brand new project that will get little activity, I’d prefer we use GitHub Actions only.
> 
> Further notes on the CI setup:
> 
>     * The way the nightly jobs are defined in CircleCI is [deprecated](https://circleci.com/docs/2.0/workflows/#scheduling-a-workflow), and will stop working in June. We should either move this to GitHub Actions, or if we want to keep using CircleCI, use their new scheduling support.
>

_Originally posted by @lb- in https://github.com/wagtail/wagtail-hallo/issues/9#issuecomment-1056739234_

**Comment by thibaudcolas** [comment]
@zerolab has done this in GitHub Actions for `wagtailmedia`:

- https://github.com/torchbox/wagtailmedia/blob/main/.github/workflows/nightly-tests.yml
- https://github.com/torchbox/wagtailmedia/blob/main/.github/report_nightly_build_failure.py

**Comment by zerolab** [comment]
Also documented on https://github.com/wagtail/wagtail/wiki/Nightly-testing-of-official-plugins

**Comment by lb-** [comment]
Not sure if I need to configure something else - will investigate. 

```

0s
Run python .github/report_nightly_build_failure.py
  python .github/report_nightly_build_failure.py
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.9.10/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.10/x64/lib
    SLACK_WEBHOOK_URL: 
Traceback (most recent call last):
Reporting to #nightly-build-failures slack channel
  File "/home/runner/work/wagtail-hallo/wagtail-hallo/.github/report_nightly_build_failure.py", line 15, in <module>
    response = requests.post(
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/requests/sessions.py", line 515, in request
    prep = self.prepare_request(req)
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/requests/sessions.py", line 443, in prepare_request
    p.prepare(
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/requests/models.py", line 318, in prepare
    self.prepare_url(url, params)
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/requests/models.py", line 392, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant http://?
Error: Process completed with exit code 1.

```

**Comment by lb-** [comment]
@zerolab could you please DM me in slack, I need to update the env var for the action.

> Slack webhook URL into the SLACK_WEBHOOK_URL environment variable.

**Comment by lb-** [comment]
should be good now

<img width="835" alt="Screen Shot 2022-03-07 at 8 34 48 am" src="https://user-images.githubusercontent.com/1396140/156945001-e6d32910-7c3f-4d48-8780-8c7f7e95989c.png">
