### ISSUE TITLE
potential - move to BSD licence 

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail-hallo#19]
When setting up this project I used the default licence from our wagtial cookie-cutter project. 

https://github.com/wagtail/cookiecutter-wagtail-package/blob/dabe4cf807c00d7ea683d215c1a9b8e637b8bbd6/cookiecutter.json#L12

However, our preferred licence is actually BSD - in the roughly formalised approach to maintained packages. 

https://paper.dropbox.com/doc/Python-Package-Maintenance-Guidelines--BcbS1tOocmhxg78lje4U19RWAg-ZDYOJ7mgnhaC47Tzu8Jn0

I have raised a PR to change the default cookie-cutter usage. 

https://github.com/wagtail/cookiecutter-wagtail-package/pull/19

However, this issue is about whether we should change the hallo package to BSD. this package is only released as an alpha so should be ok to change now.

**Comment by thibaudcolas** [comment]
Personally I would think it’s not worth the trouble.

**Comment by lb-** [comment]
No problems.
